services:
  # Banco de dados MySQL
  mysql:
    image: mysql:8.0
    container_name: case_itau_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: case_itau_db
      MYSQL_USER: case_itau_user
      MYSQL_PASSWORD: case_itau_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./case_itau_nodejs/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

  # Backend API (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: case_itau_backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=case_itau_user
      - DB_PASSWORD=case_itau_pass
      - DB_DATABASE=case_itau_db
      - NODE_ENV=development
    depends_on:
      - mysql

  # Frontend (Angular)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: case_itau_frontend
    restart: unless-stopped
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  mysql_data: 